watch_stylesheet: true
watch_config: true
debug: false

bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    animation:
      enabled: true
      duration: 400
    alignment:
      position: "top"
    blur_effect:
      enabled: true
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "home",
          "komorebi_workspaces",
          "komorebi_active_layout",
          "taskbar",
          "media",
        ]
      center: [
          "clock",
        ]
      right:
        [
          "volume",
          "microphone",
          "apps",
          "systray",
        ]

widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      system_menu: true
      power_menu: true
      blur: true
      border_color: "system"
      round_corners_type: "normal"
      menu_labels:
        about: "\ue66A  About This PC"
        system: "\uF423  System Settings"
        task_manager: "\uf437  Task Manager"
        hibernate: "\uf28e  Hibernate"
        sleep: "\u23fe  Sleep"
        restart: "\uead2  Restart"
        shutdown: "\uf011  Shutdown"
        lock: "\uea75  Lock"
        logout: "\udb80\udf43  Logout"
      menu_list:
        - { title: "\uE617  User Home", path: "~" }
        - { title: "\udb80\udd20  Download", path: "~\\Downloads" }
        - { title: "\udb80\ude1a  Documents", path: "~\\Documents" }
        - { title: "\uf03e  Pictures", path: "~\\Pictures" }

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation:
        enabled: true
      preview:
        enabled: true
        width: 250
        delay: 400
        padding: 12
      callbacks:
        on_middle: "close_app"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_workspace_btn: "\uf10c"
      label_workspace_active_btn: "\uf111"
      label_workspace_populated_btn: "\uf192"
      label_default_name: ""
      hide_empty_workspaces: false
      hide_if_offline: true

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack', 'scrolling']
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        scrolling: "\uebf7"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximized: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: 'toggle_layout_menu'
        on_middle: 'next_layout'
        on_right: 'prev_layout'
      layout_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icons: true

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uf054"
      label_expanded: "\uf078"
      label_position: "left"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: true
      show_unpinned_button: true
      show_battery: false
      show_in_popup: 1
      show_volume: false
      icons_per_row: 6
      show_network: false
      use_hook: false
      hide_icons: []
      popup:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title} - {artist}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 45
        label_alt: 80
      show_thumbnail: false
      controls_only: false
      controls_left: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 10
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%A %d %b %H:%M}"
      timezones: []
      calendar:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        holiday_color: "#FF6464"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      mute_text: "Mute"
      icons:
        - "\ue74f"
        - "\ue992"
        - "\ue993"
        - "\ue994"
        - "\ue995"
      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_mute"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"

  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span>"
      mute_text: "Mute"
      icons:
        normal: "\ue720"
        muted: "\uf12e"
      mic_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_mic_menu"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_mute"
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "\ueb03", launch: "cmd /c Taskmgr", name: "Task Manager" }
        - { icon: "\uf489", launch: "wt", name: "Windows Terminal" }
